### ISSUE TITLE
TypeError: no _dump_data is defined for class Enumerator

### ISSUE THREAD

**Issue by salimane** [moll/capistrano-rsync#23]
It seems `capistrano-rsync` is not compatible with the latest version of `capistrano 3.4.0`.

``` shell
[user@server project]$ cat Gemfile | grep cap
  gem 'capistrano', '~> 3.4.0', require: false
  gem 'capistrano-rails', '~> 1.1.2', require: false
  gem 'capistrano-bundler', '~> 1.1.4', require: false
  gem 'capistrano-rvm', '~> 0.1.2', require: false
  gem 'capistrano-sidekiq', '~> 0.4.0', require: false
  gem 'capistrano-rsync', github: 'STRML/capistrano-rsync', require: false
[user@server project]$
```

``` shell
** Execute rsync:release
cap aborted!
TypeError: no _dump_data is defined for class Enumerator
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:54:in `dump'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:54:in `on'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-rsync-1.0.2/lib/capistrano/rsync.rb:89:in `block (2 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/tasks/deploy.rake:9:in `block (2 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:16:in `invoke'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:65:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:64:in `each'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/tasks/framework.rake:64:in `block in <top (required)>'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
/usr/local/rvm/gems/ruby-2.2.1@project/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1@project/bin/cap:23:in `load'
/usr/local/rvm/gems/ruby-2.2.1@project/bin/cap:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.1@project/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1@project/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => rsync:create_release => rsync:release
The deploy has failed with an error: no _dump_data is defined for class Enumerator
** Invoke deploy:failed (first_time)
** Execute deploy:failed
[user@server project]$
```

**Comment by hiennguyenvan-agilityio** [comment]
I got same error. Anyone has solution for that?

**Comment by cscd98** [comment]
Same here!!!!!!!!

**Comment by sheadawson** [comment]
+1

**Comment by hoeni** [comment]
Same here +1

**Comment by poc7667** [comment]
any update?

**Comment by anthonyherve** [comment]
+1

**Comment by christian-fries** [comment]
Same here

**Comment by khiem-nguyen** [comment]
+1

**Comment by zuernBernhard** [comment]
same here +1

**Comment by zuernBernhard** [comment]
Works with the fork from Blakdrak - just add to your Gemfile:

`gem 'capistrano-rsync-bladrak', '~> 1.3.3'`

And then run bundle update

**Comment by khiem-nguyen** [comment]
@zuernBernhard It works. Thanks alot
But some warnings are coming out. Please fix it

```
Capistrano tasks may only be invoked once. Since task `rsync:release' was previously invoked, invoke("rsync:release") at /home/app/cl-chef/deploy/vendor/bundle/ruby/2.3.0/gems/capistrano-rsync-bladrak-1.3.8/lib/capistrano/rsync.rb:128 will be skipped.
If you really meant to run this task again, first call Rake::Task["rsync:release"].reenable
THIS BEHAVIOR MAY CHANGE IN A FUTURE VERSION OF CAPISTRANO. Please join the conversation here if this affects you.
https://github.com/capistrano/capistrano/issues/1686
Skipping task `rsync:release'.
Capistrano tasks may only be invoked once. Since task `rsync:release' was previously invoked, invoke("rsync:release") at /home/app/cl-chef/deploy/vendor/bundle/ruby/2.3.0/gems/capistrano-rsync-bladrak-1.3.8/lib/capistrano/rsync.rb:128 will be skipped.
If you really meant to run this task again, first call Rake::Task["rsync:release"].reenable
THIS BEHAVIOR MAY CHANGE IN A FUTURE VERSION OF CAPISTRANO. Please join the conversation here if this affects you.
https://github.com/capistrano/capistrano/issues/1686
```

**Comment by zuernBernhard** [comment]
hm the bladrak gem is not from me - perhaps it can be adressed in the capistrano resync repo
